#cloud-config
# Arch Linux Cloud-Init Configuration Template

hostname: ${hostname}
fqdn: ${hostname}.local

# Users configuration
users:
  - name: arch
    groups: wheel,docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}
  - name: root
    ssh_authorized_keys:
      - ${ssh_public_key}

# Network configuration
network:
  version: 2
  ethernets:
    eth0:
      addresses:
        - ${ip_address}/24
      gateway4: ${gateway}
      nameservers:
        addresses: ${dns_servers}

# Package installation
packages:
  - base
  - base-devel
  - linux
  - linux-firmware
  - networkmanager
  - openssh
  - sudo
  - vim
  - git
  - curl
  - wget
  - htop
  - docker
  - kubernetes-tools

# Services to enable
runcmd:
  - systemctl enable NetworkManager
  - systemctl start NetworkManager
  - systemctl enable sshd
  - systemctl start sshd
  - systemctl enable docker
  - echo 'Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
  - pacman -Sy
  - hostnamectl set-hostname ${hostname}

# SSH configuration
ssh_authorized_keys:
  - ${ssh_public_key}

ssh_pwauth: false

# Set timezone
timezone: UTC

# Enable password authentication (temporary)
chpasswd:
  list: |
    root:archlinux
    arch:archlinux
  expire: false